### ISSUE TITLE
Question about the pretrained RFMobilenetV2Plus model.

### ISSUE THREAD

**Issue by shawnfd** [ansleliu/LightNet#11]
Excuse me but, I'd like to ask about the RFMobilenetV2Plus pretrained model. When will you upload those pretrained model (either pretrained on imagenet or cityscape)?
I didnt's find any clue in your README.md
Thanks.

**Comment by ansleliu** [comment]
@shawnfd Hi, You can find the RFMobilenetV2Plus pretrained model in README ^_^

**Comment by shawnfd** [comment]
@ansleliu 
Thanks very much for your quick response. I found it finally!

**Comment by gshdong** [comment]
@ansleliu @shawnfd I can't find any pretrained models in your README. I only find best checkpoint. Where does your pretrained models. Can you tell me, thanks!

**Comment by fip-lab** [comment]
> @ansleliu @shawnfd I can't find any pretrained models in your README. I only find best checkpoint. Where does your pretrained models. Can you tell me, thanks!

The same to you.
