### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by villazfy** [ansleliu/LightNet#4]
File "c:\Users\Administrator\Desktop\LightNet-master\modules\_ext\__init__.py", line 2, in <module>
    from .__ext import lib as _lib, ffi as _ffi
ModuleNotFoundError: No module named 'modules._ext.__ext'

I can not find " .__ext" in your project
can you upload it?

**Comment by ansleliu** [comment]
@villazfy Naja... If you want to use "encoding", please add and build "PyTorch-Encoding" as described in [this repo](https://github.com/zhanghang1989/PyTorch-Encoding).
For more detail, please go visit you this [website](http://hangzh.com/PyTorch-Encoding/). ^_^
